//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PesXp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LOGIN_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_USER_CENTER_DIALOG          129
#define IDD_SUBMIT_SCORE_DIALOG         131
#define IDD_AGREE_SCORE_DIALOG          133
#define IDD_PLAYER_LIB_DIALOG           135
#define IDD_PLAYER_SEARCH_DIALOG        136
#define IDD_LEAGUE_INFO_DIALOG          137
#define IDD_LEAGUE_CALENDAR_DIALOG      138
#define IDD_LEAGUE_MY_TEAM_DIALOG       139
#define IDD_LEAGUE_TEAM_RANK_DIALOG     140
#define IDD_LEAGUE_ASSITANT_RANK_DIALOG 141
#define IDD_LEAGUE_GOAL_RANK_DIALOG     142
#define IDD_LEAGUE_HONOR_DIALOG         143
#define IDD_LEAGUE_MARKET_DIALOG        144
#define IDD_WAITING_DIALOG              145
#define IDR_GIF1                        155
#define IDR_GIF_WAITING                 155
#define IDC_LOGIN_BUTTON_LOGIN          1000
#define IDC_LOGIN_BUTTON_REGISTER       1001
#define IDC_LOGIN_EDIT_USER_NAME        1002
#define IDC_LOGIN_EDIT_PASSWORD         1003
#define IDC_LOGIN_TEXT_USER_NAME        1004
#define IDC_LOGIN_TEXT_PASSWORD         1005
#define IDC_LOGIN_SEPARATOR             1006
#define IDC_LOGIN_BUTTON_SUBMIT         1007
#define IDC_REG_TEXT_REG_USER_NAME      1008
#define IDC_REG_TEXT_REG_PASSWORD       1009
#define IDC_REG_TEXT_CONFIRM_PASSWORD   1010
#define IDC_REG_TEXT_QQ                 1011
#define IDC_REG_TEXT_EMAIL              1012
#define IDC_REG_TEXT_TITLE              1013
#define IDC_REG_TEXT_TIP_INFO           1014
#define IDC_REG_EDIT_USER_NAME          1015
#define IDC_REG_EDIT_PASSWORD           1016
#define IDC_REG_EDIT_CONFIRM_PASSWORD   1017
#define IDC_REG_EDIT_QQ                 1018
#define IDC_REG_EDIT_EMAIL              1019
#define IDC_BUTTON_GLORY                1021
#define IDC_BUTTON_CALENDAR             1022
#define IDC_BUTTON_LEAGUE_DOING         1023
#define IDC_UC_TEXT                     1024
#define IDC_UC_TEXT_ACCOUNT             1025
#define IDC_UC_TEXT6                    1026
#define IDC_UC_TEXT_CREDIE              1027
#define IDC_UC_TEXT7                    1028
#define IDC_UC_TEXT1                    1029
#define IDC_UC_TEXT_WIN                 1030
#define IDC_UC_TEXT8                    1031
#define IDC_UC_TEXT_EQUAL               1032
#define IDC_UC_TEXT9                    1033
#define IDC_UC_TEXT_LOSE                1034
#define IDC_UC_TEXT10                   1035
#define IDC_UC_TEXT_WIN_PERCENT         1036
#define IDC_UC_TEXT11                   1037
#define IDC_UC_TEXT_RANK                1038
#define IDC_UC_TEXT12                   1039
#define IDC_UC_TEXT2                    1040
#define IDC_UC_TEXT_NEED_CONFIRM        1041
#define IDC_UC_TEXT17                   1042
#define IDC_UC_TEXT_NOT_CONFIRM         1043
#define IDC_UC_TEXT18                   1044
#define IDC_UC_TEXT_GOAL_COUNT          1045
#define IDC_UC_TEXT13                   1046
#define IDC_UC_TEXT_LOSE_COUNT          1047
#define IDC_UC_TEXT14                   1048
#define IDC_UC_TEXT_RED_COUNT           1049
#define IDC_UC_TEXT15                   1050
#define IDC_UC_TEXT_YELLOW_COUNT        1051
#define IDC_UC_TEXT16                   1052
#define IDC_BUTTON_SUBMIT_SCORE         1053
#define IDC_UC_SEPARATOR                1054
#define IDC_UC_TEXT20                   1055
#define IDC_UC_TEXT21                   1056
#define IDC_UC_TEXT22                   1057
#define IDC_UC_TEXT24                   1058
#define IDC_UC_TEXT_LEAGUE_WIN          1059
#define IDC_UC_TEXT_LEAGUE_EQUAL        1060
#define IDC_UC_COMBO_JOIN_LEAGUE        1061
#define IDC_UC_TEXT_LEAGUE_LOSE         1062
#define IDC_BUTTON_ENTER_MY_LEAGUE      1063
#define IDC_UC_TEXT3                    1064
#define IDC_UC_TEXT4                    1065
#define IDC_UC_TEXT5                    1066
#define IDC_UC_TEXT19                   1067
#define IDC_UC_TEXT25                   1068
#define IDC_UC_TEXT29                   1069
#define IDC_UC_TEXT_PLAYER_COUNT        1070
#define IDC_UC_TEXT_LEAGUE_INFO         1071
#define IDC_UC_TEXT_LEAGUE_END_DATE     1071
#define IDC_UC_TEXT_SIGN_COUNT          1072
#define IDC_UC_TEXT23                   1073
#define IDC_UC_TEXT_LEAGUE_WIN_PERCENT  1074
#define IDC_UC_TEXT_LEAGUE_RANK         1075
#define IDC_UC_COMBO_OTHER_LEAGUE       1076
#define IDC_UC_TEXT26                   1077
#define IDC_UC_TEXT_THE_FIRST           1078
#define IDC_BUTTON_WATCH_LEAGUE         1079
#define IDC_UC_COMBO_SIGN_LEAGUE        1080
#define IDC_UC_TEXT30                   1081
#define IDC_BUTTON_LEAGUE_SIGN          1082
#define IDC_UC_TEXT31                   1083
#define IDC_UC_TEXT28                   1084
#define IDC_UC_TEXT27                   1085
#define IDC_UC_TEXT_THE_END             1086
#define IDC_UC_FLAG                     1087
#define IDC_BUTTON_AGREE_SCORE          1088
#define IDC_SUBMIT_TEXT                 1088
#define IDC_UC_TEXT32                   1089
#define IDC_SUBMIT_TEXT1                1089
#define IDC_UC_TEXT_LEAGUE_MONEY        1090
#define IDC_SUBMIT_TEXT2                1090
#define IDC_SUBMIT_TEXT3                1091
#define IDC_SUBMIT_TEXT4                1092
#define IDC_SUBMIT_TEXT5                1093
#define IDC_SUBMIT_TEXT6                1094
#define IDC_SUBMIT_TEXT_OWNER_TEAM      1095
#define IDC_SUBMIT_TEXT_TIP_INFO        1096
#define IDC_SUBMIT_TEXT_OWNER_TEAM2     1096
#define IDC_COMBO_OWNER_GOAL            1097
#define IDC_SUBMIT_TEXT_OWNER_TEAM3     1097
#define IDC_COMBO_OWNER_GOAL_PLAYER     1098
#define IDC_COMBO_OWNER_ASSIST_PLAYER   1099
#define IDC_COMBO_OWNER_RED_PLAYER      1100
#define IDC_COMBO_OWNER_YELLOW_PLAYER   1101
#define IDC_COMB_GUEST_TEAM_LIST        1102
#define IDC_SUBMIT_TEXT_OWNER_TEAM4     1102
#define IDC_COMBO_GUEST_GOAL            1103
#define IDC_COMBO_GUEST_GOAL_PLAYER     1104
#define IDC_COMBO_GUEST_ASSIST_PLAYER   1105
#define IDC_COMBO_GUEST_RED_PLAYER      1106
#define IDC_COMBO_GUEST_YELLOW_PLAYER   1107
#define IDC_PLAYER_LIST                 1108
#define IDC_PLAYER_LIST1                1109
#define IDC_PLAYER_LIST2                1110
#define IDC_PLAYER_LIST3                1111
#define IDC_PLAYER_LIST4                1112
#define IDC_PLAYER_LIST5                1113
#define IDC_PLAYER_LIST6                1114
#define IDC_PLAYER_LIST7                1115
#define IDC_AGREE_SEPARATOR             1117
#define IDC_AGREE_TEXT_TIP_INFO         1118
#define IDC_PLAYER_LIB_TREE             1120
#define IDC_PLAYER_LIB_LIST             1123
#define IDC_PLAYER_LIB_SEPARATOR1       1124
#define IDC_PLAYER_LIB_SEPARATOR2       1125
#define IDC_PIC_STATIC                  1126
#define IDC_PLAYER_LIB_PIC              1126
#define IDC_STATIC_1                    1129
#define IDC_STATIC_2                    1130
#define IDC_STATIC_3                    1131
#define IDC_STATIC_4                    1132
#define IDC_STATIC_5                    1133
#define IDC_STATIC_6                    1134
#define IDC_STATIC_7                    1135
#define IDC_STATIC_8                    1136
#define IDC_STATIC_9                    1137
#define IDC_STATIC_10                   1138
#define IDC_STATIC_11                   1139
#define IDC_STATIC_12                   1140
#define IDC_STATIC_13                   1141
#define IDC_STATIC_14                   1142
#define IDC_STATIC_15                   1143
#define IDC_STATIC_16                   1144
#define IDC_STATIC_17                   1145
#define IDC_STATIC_18                   1146
#define IDC_STATIC_19                   1147
#define IDC_STATIC_20                   1148
#define IDC_STATIC_21                   1149
#define IDC_STATIC_22                   1150
#define IDC_STATIC_23                   1151
#define IDC_STATIC_24                   1152
#define IDC_STATIC_25                   1153
#define IDC_STATIC_26                   1154
#define IDC_STATIC_27                   1155
#define IDC_STATIC_28                   1156
#define IDC_STATIC_29                   1157
#define IDC_STATIC_30                   1158
#define IDC_STATIC_31                   1159
#define IDC_STATIC_32                   1160
#define IDC_STATIC_33                   1161
#define IDC_STATIC_34                   1162
#define IDC_STATIC_35                   1163
#define IDC_STATIC_36                   1164
#define IDC_STATIC_37                   1165
#define IDC_STATIC_38                   1166
#define IDC_STATIC_39                   1167
#define IDC_STATIC_40                   1168
#define IDC_STATIC_41                   1169
#define IDC_STATIC_42                   1170
#define IDC_STATIC_43                   1171
#define IDC_STATIC_44                   1172
#define IDC_STATIC_45                   1173
#define IDC_CHECK1                      1174
#define IDC_CHECK_NAME                  1174
#define IDC_CHECK2                      1175
#define IDC_CHECK_WE_NAME               1175
#define IDC_CHECK3                      1176
#define IDC_CHECK_COUNTRY               1176
#define IDC_CHECK4                      1177
#define IDC_CHECK_CLUB                  1177
#define IDC_CHECK5                      1178
#define IDC_CHECK_POS                   1178
#define IDC_CHECK6                      1179
#define IDC_CHECK_AGE                   1179
#define IDC_CHECK7                      1180
#define IDC_CHECK_FOOT                  1180
#define IDC_CHECK8                      1181
#define IDC_CHECK_VALUE                 1181
#define IDC_CHECK9                      1182
#define IDC_CHECK_HEIGHT                1182
#define IDC_CHECK10                     1183
#define IDC_CHECK_WEIGHT                1183
#define IDC_CHECK11                     1184
#define IDC_CHECK_BIRTH                 1184
#define IDC_CHECK12                     1185
#define IDC_CHECK_CONS                  1185
#define IDC_BUTTON1                     1186
#define IDC_BUTTON_SEARCH               1186
#define IDC_JOIN_LEAGUE                 1186
#define IDC_MARKET_BUTTON               1186
#define IDC_EDIT1                       1187
#define IDC_EDIT_NAME                   1187
#define IDC_EDIT2                       1188
#define IDC_EDIT_WE_NAME                1188
#define IDC_EDIT3                       1189
#define IDC_CHECK_SIDE                  1189
#define IDC_EDIT4                       1190
#define IDC_DATETIMEPICKER1             1198
#define IDC_DATETIMEPICKER_BIRTH        1198
#define IDC_EDIT5                       1200
#define IDC_SPIN2                       1201
#define IDC_SPIN3                       1202
#define IDC_SPIN4                       1203
#define IDC_SPIN5                       1204
#define IDC_SPIN6                       1205
#define IDC_SPIN7                       1206
#define IDC_SPIN8                       1207
#define IDC_SPIN_VALUE_MIN              1207
#define IDC_SPIN9                       1208
#define IDC_SPIN_VALUE_MAX              1208
#define IDC_EDIT6                       1209
#define IDC_SPIN_AGE_MIN                1209
#define IDC_EDIT7                       1210
#define IDC_SPIN_AGE_MAX                1210
#define IDC_EDIT8                       1211
#define IDC_SPIN_WEIGHT_MIN             1211
#define IDC_EDIT9                       1212
#define IDC_EDITIDC_EDITIDC_EDIT_VALUE_MIN 1212
#define IDC_EDITIDC_EDITIDC_EDIT_VALUE_MAX 1213
#define IDC_EDITIDC_EDIT_AGE_MIN        1214
#define IDC_COMBO2                      1215
#define IDC_COMBO_CONTINET              1215
#define IDC_EDITIDC_EDITIDC_EDIT_AGE_MAX 1216
#define IDC_SPIN_WEIGHT_MAX             1217
#define IDC_LEAGUE_INFO_PROGRESS_TEXT   1217
#define IDC_EDIT_WEIGHT_MIN             1218
#define IDC_LEAGUE_INFO_START_TEXT      1218
#define IDC_EDITIDC_EDIT_WEIGHT_MAX     1219
#define IDC_LEAGUE_INFO_STOP_TEXT       1219
#define IDC_SPIN_HEIGHT_MIN             1220
#define IDC_LEAGUE_INFO_POST_TEXT       1220
#define IDC_SPIN_HEIGHT_MAX             1221
#define IDC_LEAGUE_INFO_TEAM_COUNT_TEXT 1221
#define IDC_EDIT_HEIGHT_MIN             1222
#define IDC_LEAGUE_INFO_MATCH_COUNT_TEXT 1222
#define IDC_COMBO_COUNTRY               1223
#define IDC_LEAGUE_INFO_GOAL_TEXT       1223
#define IDC_COMBO_CONTIENT_CLUB         1224
#define IDC_LEAGUE_INFO_ASSITANT_TEXT   1224
#define IDC_LEAGUE_INFO_FIRST_TEXT      1225
#define IDC_COMBO_CLUB                  1226
#define IDC_LEAGUE_INFO_LAST_TEXT       1226
#define IDC_COMBO_POS                   1227
#define IDC_LEAGUE_INFO_RED_TEXT        1227
#define IDC_COMBO_CONS                  1228
#define IDC_LEAGUE_INFO_YELLOW_TEXT     1228
#define IDC_COMBO_FOOT                  1229
#define IDC_LIST_MY_TEAM                1229
#define IDC_EDIT_HEIGHT_MAX             1230
#define IDC_MY_TEAM_NAME_TEXT           1230
#define IDC_COMBO_FOOT_SIDE             1231
#define IDC_MY_TEAM_MONEY_TEXT          1231
#define IDC_MY_TEAM_RANK_TEXT           1232
#define IDC_MY_TEAM_WIN_PERCENT_TEXT    1233
#define IDC_MY_TEAM_WIN_COUNT_TEXT      1234
#define IDC_MY_TEAM_TIE_COUNT_TEXT      1235
#define IDC_MY_TEAM_LOSE_COUNT_TEXT     1236
#define IDC_MY_TEAM_GOAL_TEXT           1237
#define IDC_MY_TEAM_ASSITANT_TEXT       1238
#define IDC_MY_TEAM_RED_TEXT            1239
#define IDC_MY_TEAM_YELLOW_TEXT         1240
#define IDC_LIST_CALENDAR               1241
#define IDC_LIST_TEAM_RANK              1242
#define IDC_LIST_GOAL_RANK              1243
#define IDC_LIST_ASSITANT_RANK          1244
#define IDC_LIST_HONOR                  1245
#define IDC_LIST_MARKET                 1246
#define IDC_LIST_MY_MARKET              1247
#define IDC_WAITING_MESSAGE_TEXT        1250
#define IDC_WAITING_GIF                 1252

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
